export const SET_USER = "SET_USER";
export const SET_SERVER = "SET_SERVER";
export const SET_SPACE = "SET_SPACE";
export const SET_GROUP = "SET_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const SET_ACTIVE_SPACE_ID = "SET_ACTIVE_SPACE_ID";
export const SET_ACTIVE_GROUP_ID = "SET_ACTIVE_GROUP_ID";
export const ADD_ARCHIVED_MESSAGE = "ADD_ARCHIVED_MESSAGE";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_LOCAL_USER_DETAIL = "SET_LOCAL_USER_DETAIL";
export const SET_MASTER_CHANNEL_DETAIL = "SET_MASTER_CHANNEL_DETAIL";
export const SET_ACTIVE_SERVER_ID = "SET_ACTIVE_SERVER_ID";


export const ADD_LOCAL_TRACK = 'ADD_LOCAL_TRACK';
export const UPDATE_LOCAL_TRACK = 'UPDATE_LOCAL_TRACK';
export const REMOVE_LOCAL_TRACK = 'REMOVE_LOCAL_TRACK';
export const LOCAL_TRACK_ACTION = 'LOCAL_TRACK_ACTION';

export const ADD_CONFERENCE = 'ADD_CONFERENCE';
export const ADD_CONNECTION = 'ADD_CONNECTION'
export const REMOVE_CONFERENCE = 'REMOVE_CONFERENCE';
export const GET_CONFERENCE = 'GET_CONFERENCE';


export const CREATE_LOCAL_TRACKS = "CREATE_LOCAL_TRACKS";
export const REMOVE_CONNECTION = "REMOVE_CONNECTION";


//connection
export const CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";
export const CONNECTION_FAILED = "CONNECTION_FAILED";

// confernece
export const CONFERENCE_JOINED = "CONFERENCE_JOINED";
export const CONFERENCE_LEFT = "CONFERENCE_LEFT";
export const CONFERENCE_FAILED = "CONFERENCE_FAILED";
export const CONFERENCE_ERROR = "CONFERENCE_ERROR";

// track
export const TRACK_ADDED = "TRACK_ADDED";
export const TRACK_REMOVED = "TRACK_REMOVED";
export const TRACK_MUTE_CHANGED = "TRACK_MUTE_CHANGED";

export const CONNECTION_DISCONNECT = "disconnect";


export const PASSWORD_REQUIRED = "PASSWORD_REQUIRED";


export const LOCAL_TRACK_MUTE_CHANGED = "LOCAL_TRACK_MUTE_CHANGED";
export const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT";
export const SELECT_PARTICIPANT = "SELECT_PARTICIPANT";

export const ADD_REMOTE_TRACK = "ADD_REMOTE_TRACK";
export const UPDATE_REMOTE_TRACK = "UPDATE_REMOTE_TRACK";
export const REMOVE_REMOTE_TRACK = "REMOVE_REMOTE_TRACK";
export const REMOTE_TRACK_MUTE_CHANGED = "REMOTE_TRACK_MUTE_CHANGED";

export const SET_LAYOUT = "SET_LAYOUT";
export const SET_FULLSCREEN_MODE = "SET_FULLSCREEN_MODE";
export const CLEAR_ALL = "CLEAR_ALL";
export const SET_ACTIVE_CONTROL = "SET_ACTIVE_CONTROL";

export const SET_PROFILE = "SET_PROFILE";
export const SET_SELECTED_PEOPLE = "SET_SELECTED_PEOPLE";


export const SET_MICROPHONE = "SET_MICROPHONE";
export const SET_SPEAKER = "SET_SPEAKER";
export const SET_RESOLUTION = "SET_RESOLUTION";
export const SET_CAMERA = "SET_CAMERA";

export const UNREAD_MESSAGES = "UNREAD_MESSAGES";
export const SET_PIN_PARTICIPANT = "SET_PIN_PARTICIPANT";
export const SET_PRESENTER = "SET_PRESENTER";
export const ADD_COLOR = "ADD_COLOR";
export const REMOVE_COLOR = "REMOVE_COLOR";
export const SET_AUDIO_LEVEL = "SET_AUDIO_LEVEL";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";

export const SET_GOOGLE_API_STATE = "SET_GOOGLE_API_STATE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_MEETING_TITLE = "SET_MEETING_TITLE";
export const SET_DISCONNECTED = "SET_DISCONNECTED";

export const SET_PRESENTATION_TYPE = "SET_PRESENTATION_TYPE";
export const SET_HAND_RAISE = "SET_HAND_RAISE";
export const SET_DOMINANT_SPEAKER = "SET_DOMINANT_SPEAKER";
export const REMOVE_ALL_REMOTE_TRACK = "REMOVE_ALL_REMOTE_TRACK";
export const REMOVE_ALL_LOCAL_TRACK = "REMOVE_ALL_LOCAL_TRACK";
export const SET_USER_IN_VICINITY = "SET_USER_IN_VICINITY";

export const ADD_EVENTS = "ADD_EVENTS";
export const SET_EVENTS = "SET_EVENTS";

export const ADD_TOKEN = "ADD_TOKEN";
export const LOG_OUT = "LOG_OUT";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USERNAME = "SET_USERNAME";
export const SET_EMAIL_ID = "SET_EMAIL_ID";
export const SET_IMAGE_URL = "SET_IMAGE_URL";

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCESS";
export const SEND_OTP_FAILED = "SEND_OTP_FAILED";
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";

export const FETCH_NOTES = "FETCH_NOTES";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILED = "FETCH_NOTES_FAILED";

export const ADD_NOTES = "ADD_NOTES";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_FAILED = "ADD_NOTES_FAILED";

export const UPDATE_NOTES = "UPDATE_NOTES";
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS";
export const UPDATE_NOTES_FAILED = "UPDATE_NOTES_FAILED";

export const LOADER = "LOADER"

export const TOGGLE_INVITE_MEMBERS_SCREEN = "TOGGLE_INVITE_MEMBERS_SCREEN"
export const FETCH_SUGGESTED_MEMBERS = "FETCH_SUGGESTED_MEMBERS";
export const FETCH_SUGGESTED_MEMBERS_SUCCESS = "FETCH_SUGGESTED_MEMBERS_SUCCESS";
export const FETCH_SUGGESTED_MEMBERS_FAILED = "FETCH_SUGGESTED_MEMBERS_FAILED";

export const SET_ACTIVE_CONFERENCE_ID = "SET_ACTIVE_CONFERENCE_ID";

//Calendar Integration
export const CHECK_INTEGRATION_STATUS = "CHECK_INTEGRATION_STATUS"
export const CHECK_INTEGRATION_STATUS_SUCCESS = "CHECK_INTEGRATION_STATUS_SUCCESS"
export const CHECK_INTEGRATION_STATUS_FAILURE = "CHECK_INTEGRATION_STATUS_FAILURE";
export const FETCH_INTEGRATION_LINK = "FETCH_INTEGRATION_LINK";
export const FETCH_INTEGRATION_LINK_SUCCESS = "FETCH_INTEGRATION_LINK_SUCCESS";
export const FETCH_INTEGRATION_LINK_FAILURE = "FETCH_INTEGRATION_LINK_FAILURE";
export const TOGGLE_CALENDAR_SCREEN = "TOGGLE_CALENDAR_SCREEN"
export const VERIFY_CREDENTIALS = "VERIFY_CREDENTIALS";
export const VERIFY_CREDENTIALS_SUCCESS = "VERIFY_CREDENTIALS_SUCCESS";
export const VERIFY_CREDENTIALS_FAILURE = "VERIFY_CREDENTIALS_FAILURE";
export const TOGGLE_AUTH_CODE_SCREEN = "TOGGLE_AUTH_CODE_SCREEN"
export const SET_FILTER_DATE = "SET_FILTER_DATE"


// activity of Group notes
export const FETCH_GROUP_DATA_REQUEST = "FETCH_GROUP_DATA_REQUEST";
export const FETCH_GROUP_DATA_SUCCESS = "FETCH_GROUP_NOTES_SUCCESS";
export const FETCH_GROUP_DATA_FAILURE = "FETCH_GROUP_NOTES_FAILURE";


// ACTIOn ITEMS 
export const ADD_ACTION_ITEM = "ADD_ACTION_ITEM";
export const ADD_ACTION_ITEM_SUCCESS = "ADD_ACTION_ITEM_SUCCESS";
export const ADD_ACTION_ITEM_FAILED = "ADD_ACTION_ITEM_FAILED";



